# QuickStocks Configuration

# Database Configuration
database:
  provider: sqlite # sqlite | mysql | postgres
  sqlite:
    file: plugins/QuickStocks/data.db
  mysql:
    host: 127.0.0.1
    port: 3306
    database: QuickStocks
    user: root
    password: ""
    useSSL: false
  postgres:
    host: 127.0.0.1
    port: 5432
    database: QuickStocks
    user: postgres
    password: ""

# Features Configuration
features:
  historyEnabled: true
  topListWindowHours: 24

# Market Configuration
market:
  updateInterval: 5 # seconds
  startOpen: true
  defaultStocks: true

# Market Device Configuration
marketDevice:
  recipe:
    enabled: false # Enable crafting recipe for Market Device
    shapedRecipe: true # Use shaped recipe (3x3 grid)

# Analytics Configuration
analytics:
  lambda: 0.94
  defaultWindowsMinutes:
    change: 1440  # 24 hours
    volatility: 1440  # 24 hours  
    correlation: 1440  # 24 hours