# QuickStocks Configuration

# Database Configuration
database:
  provider: sqlite # sqlite | mysql | postgres
  sqlite:
    file: plugins/QuickStocks/data.db
  mysql:
    host: 127.0.0.1
    port: 3306
    database: QuickStocks
    user: root
    password: ""
    useSSL: false
  postgres:
    host: 127.0.0.1
    port: 5432
    database: QuickStocks
    user: postgres
    password: ""

# Features Configuration
features:
  historyEnabled: true
  topListWindowHours: 24

# Market Configuration
market:
  updateInterval: 5 # seconds
  startOpen: true
  defaultStocks: true

# Backup Configuration
backup:
  enabled: true # Enable automated backups
  dailyBackup: true # Perform daily backups automatically
  emergencyBackup: true # Backup on plugin shutdown
  retentionDays: 30 # Days to keep backup files

# Security & Concurrency Configuration
security:
  maxRetries: 3 # Max retries for optimistic locking conflicts
  transactionTimeout: 30 # Transaction timeout in seconds
  auditEnabled: true # Enable integrity auditing

# Market Device Configuration
marketDevice:
  recipe:
    enabled: false # Enable crafting recipe for Market Device
    shapedRecipe: true # Use shaped recipe (3x3 grid)