# QuickStocks Configuration

# Database Configuration
database:
  provider: sqlite # sqlite | mysql | postgres
  sqlite:
    file: plugins/QuickStocks/data.db
  mysql:
    host: 127.0.0.1
    port: 3306
    database: QuickStocks
    user: root
    password: ""
    useSSL: false
  postgres:
    host: 127.0.0.1
    port: 5432
    database: QuickStocks
    user: postgres
    password: ""

# Features Configuration
features:
  historyEnabled: true
  topListWindowHours: 24

# bStats Metrics Configuration
metrics:
  enabled: true  # Enable anonymous usage statistics (bStats)

# NOTE: Market, Market Device, Analytics, Trading, and Companies configurations
# have been moved to separate files:
# - market.yml - Market, Market Device, and Analytics settings
# - trading.yml - Trading economy settings
# - companies.yml - Companies/Corporations settings
