# QuickStocks Configuration

# Database Configuration
database:
  provider: sqlite # sqlite | mysql | postgres
  sqlite:
    file: plugins/QuickStocks/data.db
  mysql:
    host: 127.0.0.1
    port: 3306
    database: QuickStocks
    user: root
    password: ""
    useSSL: false
  postgres:
    host: 127.0.0.1
    port: 5432
    database: QuickStocks
    user: postgres
    password: ""

# Features Configuration
features:
  historyEnabled: true
  topListWindowHours: 24

# Market Configuration
market:
  updateInterval: 5 # seconds
  startOpen: true
  defaultStocks: true
  
  # Price growth threshold configuration
  priceThreshold:
    enabled: true
    # Maximum price change per update before dampening kicks in (as percentage, e.g., 0.15 = 15%)
    maxChangePercent: 0.15
    # Price threshold above which dampening starts (multiplier of initial price, e.g., 5.0 = 500% of initial)
    priceMultiplierThreshold: 5.0
    # Dampening factor when threshold is exceeded (0.1 = reduce impact to 10%)
    dampeningFactor: 0.3
    # Minimum trading volume required to ignore threshold (trades per update cycle)
    minVolumeThreshold: 100
    # How quickly dampening decreases when volume increases (higher = more sensitive to volume)
    volumeSensitivity: 0.5

# Market Device Configuration
marketDevice:
  recipe:
    enabled: false # Enable crafting recipe for Market Device
    shapedRecipe: true # Use shaped recipe (3x3 grid)

# Trading Economy Configuration
trading:
  fee:
    mode: percent   # percent | flat | mixed
    percent: 0.25   # % of notional
    flat: 0.0
  limits:
    maxOrderQty: 10000
    maxNotionalPerMinute: 250000
    perPlayerCooldownMs: 750
  circuitBreakers:
    enable: true
    levels: [7, 13, 20]     # halt thresholds in % move from daily open
    haltMinutes: [15, 15, -1] # -1 = rest of session
  orders:
    allowMarket: true
    allowLimit: true
    allowStop: true
  slippage:
    mode: linear            # none | linear | sqrtImpact
    k: 0.0005               # impact coefficient (tune)