name: QuickStocks
main: com.example.quickstocks.QuickStocksPlugin
version: 1.0.0-SNAPSHOT
api-version: "1.21"
authors:
  - maksy
description: "QuickStocks - Paper plugin for Minecraft 1.21.8"

commands:
  stocks:
    description: "View stock market information and quotes"
    usage: "/stocks [symbol|material]"
    aliases: [stock, quote]
  crypto:
    description: "Create and manage custom cryptocurrency instruments"
    usage: "/crypto create <symbol> <name>"
  market:
    description: "Open the market interface and view trading information"
    usage: "/market [symbol|material]"
    aliases: [trading, trade]
  marketdevice:
    description: "Grant Market Link Device items to players"
    usage: "/marketdevice give [player]"
    aliases: [mdevice]
    
permissions:
  quickstocks.command.crypto.create:
    description: "Allows players to create custom cryptocurrency instruments"
    default: false
  maksy.stocks.crypto.create:
    description: "Allows players to create custom cryptocurrency instruments (legacy)"
    default: false
  maksy.stocks.marketdevice.give:
    description: "Allows giving Market Link Device items to players"
    default: op

