name: QuickStocks
main: com.example.quickstocks.QuickStocksPlugin
version: 1.0.0-SNAPSHOT
api-version: "1.21"
authors:
  - maksy
description: "QuickStocks - Paper plugin for Minecraft 1.21.8"

commands:
  stocks:
    description: "View stock market information and quotes"
    usage: "/stocks [symbol|material]"
    aliases: [stock, quote]
  crypto:
    description: "Create and manage custom cryptocurrency instruments"
    usage: "/crypto create <symbol> <name>"
  wallet:
    description: "Manage your wallet balance"
    usage: "/wallet [balance|add|set] [amount]"
    aliases: [money, balance]
  market:
    description: "Browse and trade in the market"
    usage: "/market [browse|buy|sell|portfolio|history]"
    aliases: [trade, trading]
  marketdevice:
    description: "Grant Market Link Device items to players"
    usage: "/marketdevice give [player]"
    aliases: [mdevice]
    
permissions:
  quickstocks.command.crypto.create:
    description: "Allows players to create custom cryptocurrency instruments"
    default: false
  maksy.stocks.crypto.create:
    description: "Allows players to create custom cryptocurrency instruments (legacy)"
    default: false
  maksy.stocks.marketdevice.give:
    description: "Allows giving Market Link Device items to players"
    default: op
  quickstocks.wallet.add:
    description: "Allows players to add money to their wallet"
    default: op
  quickstocks.wallet.set:
    description: "Allows players to set wallet balance"
    default: op

