name: QuickStocks
main: net.cyberneticforge.quickstocks.QuickStocksPlugin
version: 0.0.3
api-version: "1.21"
authors:
  - MaksyKun
description: "QuickStocks - Paper plugin for Minecraft 1.21.8"
load: POSTWORLD
softdepend: [ChestShop, WorldGuard]

commands:
  quickstocks:
    description: "QuickStocks plugin management commands"
    usage: "/quickstocks <reload>"
    aliases: [qs]
  crypto:
    description: "Create and manage custom cryptocurrency instruments"
    usage: "/crypto create <symbol> <name>"
    permission: quickstocks.command.crypto
    default: false
  wallet:
    description: "Manage your wallet balance"
    usage: "/wallet [balance|add|set] [amount]"
    aliases: [money, balance]
    permission: quickstocks.command.wallet
    default: true
  market:
    description: "Browse and trade in the market"
    usage: "/market [browse|buy|sell|portfolio|history|watchlist]"
    aliases: [trade, trading]
    permission: quickstocks.command.market
    default: true
  marketdevice:
    description: "Grant Market Link Device items to players"
    usage: "/marketdevice give [player]"
    aliases: [mdevice]
    permission: quickstocks.command.marketdevice
    default: false
  watch:
    description: "Manage your stock watchlist"
    usage: "/watch [add|remove|list|info|clear] [symbol]"
    aliases: [watchlist, wl]
    permission: quickstocks.command.watch
    default: true
  company:
    description: "Manage companies and corporations"
    usage: "§cThis feature is currently disabled."
    aliases: [corp, corporation]
    permission: quickstocks.command.company
    default: true
    
permissions:
  quickstocks.admin.reload:
    description: "Allows reloading QuickStocks configurations and services"
    default: op
  quickstocks.command.crypto.create:
    description: "Allows players to create custom cryptocurrency instruments"
    default: false
  quickstocks.stocks.crypto.create:
    description: "Allows players to create custom cryptocurrency instruments (legacy)"
    default: false
  quickstocks.stocks.marketdevice.give:
    description: "Allows giving Market Link Device items to players"
    default: op
  quickstocks.wallet.add:
    description: "Allows players to add money to their wallet"
    default: op
  quickstocks.wallet.set:
    description: "Allows players to set wallet balance"
    default: op
  quickstocks.company.create:
    description: "Allows players to create companies"
    default: true
  quickstocks.company.manage:
    description: "Allows players to manage companies they are part of"
    default: true
  quickstocks.admin.audit:
    description: "Allows access to database audit and repair commands"
    default: op

