name: QuickStocks
main: com.example.quickstocks.QuickStocksPlugin
version: 1.0.0-SNAPSHOT
api-version: "1.21"
authors:
  - maksy
description: "QuickStocks - Paper plugin for Minecraft 1.21.8"

commands:
  stocks:
    description: "View stock market information and quotes"
    usage: "/stocks [symbol|material]"
    aliases: [stock, quote]
  crypto:
    description: "Create and manage custom cryptocurrency instruments"
    usage: "/crypto create <symbol> <name>"
    
permissions:
  maksy.stocks.crypto.create:
    description: "Allows players to create custom cryptocurrency instruments"
    default: false

